# Generated by Django 2.1 on 2019-07-28 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_post_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comment',
        ),
        migrations.AddField(
            model_name='post',
            name='comment',
            field=models.ManyToManyField(blank=True, to='home.Comment'),
        ),
    ]
